// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_auth_api_keys from "./routes/api/auth/api-keys.ts";
import * as $api_auth_api_keys_id_ from "./routes/api/auth/api-keys/[id].ts";
import * as $api_auth_api_keys_id_usage from "./routes/api/auth/api-keys/[id]/usage.ts";
import * as $api_demo_api_keys from "./routes/api/demo/api-keys.ts";
import * as $api_demo_validate_key from "./routes/api/demo/validate-key.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $mod from "./islands/mod.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/auth/api-keys.ts": $api_auth_api_keys,
    "./routes/api/auth/api-keys/[id].ts": $api_auth_api_keys_id_,
    "./routes/api/auth/api-keys/[id]/usage.ts": $api_auth_api_keys_id_usage,
    "./routes/api/demo/api-keys.ts": $api_demo_api_keys,
    "./routes/api/demo/validate-key.ts": $api_demo_validate_key,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/mod.ts": $mod,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
